//! `attend` clap-derive command surface.
//!
//! This module is the canonical source for the runtime `--help` text and
//! the markdown reference at `docs/cli/attend.md` (generated by
//! `bin/gen-docs.rs`). Doc comments here become help strings; edit them
//! in one place and both surfaces update on rebuild.
//!
//! Kept dependency-free of the rest of the crate so it can be `#[path]`-
//! shared with the `gen-docs` bin without dragging in `cmd::*`, `config`,
//! etc.

use clap::{Parser, Subcommand};

#[derive(Parser)]
#[command(
    name = "attend",
    version = concat!(env!("CARGO_PKG_VERSION"), " (", env!("ATTEND_COMMIT"), ")"),
    about = "Active awareness for Claude Code sessions",
    long_about = None,
    disable_help_subcommand = true,
)]
pub(crate) struct Cli {
    #[command(subcommand)]
    pub(crate) command: Option<Commands>,
}

#[derive(Subcommand)]
pub(crate) enum Commands {
    /// Start the sensor loop (use with Monitor for async delivery)
    Run {
        /// Replay backlog signals on startup before normal cadence
        #[arg(long)]
        catchup: bool,
    },

    /// List active Claude Code sessions and focus groups
    Peers,

    /// Read pending messages from peers
    Inbox {
        /// Specific message id to read in detail (omit to list inbox)
        msg_id: Option<String>,

        /// Max messages per page, newest first
        #[arg(long, default_value_t = 25)]
        limit: usize,

        /// Page number; 1 = newest. Higher numbers walk back into history.
        #[arg(long, default_value_t = 1)]
        page: usize,

        /// Cursor: only show messages older than this unix timestamp
        #[arg(long, value_name = "TS")]
        before: Option<u64>,
    },

    /// Show running instances, signals, and focus state
    Status,

    /// List all sensors — built-in and config-defined script sensors
    Sensors,

    /// Send a signal to peer sessions (defaults to #open base channel)
    Send {
        /// Force broadcast (every peer + every Aaron session)
        #[arg(long)]
        broadcast: bool,

        /// Scope send to a specific project path
        #[arg(long, value_name = "PATH")]
        to: Option<String>,

        /// Scope send to a named focus group
        #[arg(long, value_name = "NAME")]
        focus: Option<String>,

        /// Thread reply to a specific signal id (use `attend reply` instead — it auto-threads)
        #[arg(long, value_name = "ID", hide = true)]
        re: Option<String>,

        /// Message body (must follow all flags)
        #[arg(trailing_var_arg = true, allow_hyphen_values = true)]
        message: Vec<String>,
    },

    /// Reply to the most recent peer message (auto-threaded)
    Reply {
        /// Force broadcast
        #[arg(long)]
        broadcast: bool,

        /// Scope send to a specific project path
        #[arg(long, value_name = "PATH")]
        to: Option<String>,

        /// Scope send to a named focus group
        #[arg(long, value_name = "NAME")]
        focus: Option<String>,

        /// Message body (must follow all flags)
        #[arg(trailing_var_arg = true, allow_hyphen_values = true)]
        message: Vec<String>,
    },

    /// Launch the interactive chat TUI (ADR-120)
    Chat {
        /// Arguments passed through to the `attend-chat` binary
        #[arg(trailing_var_arg = true, allow_hyphen_values = true)]
        passthrough: Vec<String>,
    },

    /// Manage attention groups (default: list joined groups)
    Focus {
        #[command(subcommand)]
        sub: Option<FocusCmd>,
    },

    /// Activate a named scene (reconfigure focus groups)
    Scene {
        /// Scene name (try `attend scenes` to list)
        name: String,
    },

    /// List available scenes
    Scenes,

    /// Survey session history and derive engagement config
    Tune {
        /// Write derived values to the user config
        #[arg(long)]
        apply: bool,
    },

    /// Audit sensor permissions against settings.json (default: audit)
    Permissions {
        #[command(subcommand)]
        sub: Option<PermissionsCmd>,
    },

    /// Reap signal files whose owning project is gone, and prune empty
    /// project dirs. Messages are never removed by age — lifetime is bound
    /// to project liveness (ADR-136).
    Cleanup {
        /// List what would be removed without deleting
        #[arg(long, short = 'n')]
        dry_run: bool,

        /// Remove every signal file regardless of project liveness
        #[arg(long)]
        all: bool,
    },

    /// Manage configuration (default: show)
    Config {
        #[command(subcommand)]
        sub: Option<ConfigCmd>,
    },
}

/// Subcommands for `attend focus`. With no subcommand, defaults to `list`.
#[derive(Subcommand)]
pub(crate) enum FocusCmd {
    /// Join a focus group
    On {
        /// Group name
        name: String,
        /// Pin so it persists across scene changes
        #[arg(long)]
        pin: bool,
    },

    /// Leave a focus group
    Off {
        /// Group name
        name: String,
    },

    /// Leave every joined group
    Clear,

    /// Pin a group so it persists across scene changes
    Pin {
        name: String,
    },

    /// Unpin a group
    Unpin {
        name: String,
    },

    /// Dissolve a group (remove for every peer)
    Dissolve {
        name: String,
    },

    /// Show every available group
    All,

    /// List joined groups (default action)
    List,
}

/// Subcommands for `attend permissions`. With no subcommand, defaults to `audit`.
#[derive(Subcommand)]
pub(crate) enum PermissionsCmd {
    /// Compare each sensor's `requires:` against settings.json
    Audit,
}

/// Subcommands for `attend config`. With no subcommand, defaults to `show`.
#[derive(Subcommand)]
pub(crate) enum ConfigCmd {
    /// Write a default config file to the user scope
    Init,

    /// Display the current effective configuration (default)
    Show,

    /// Print the user/project config file paths
    Path,

    /// Validate the config file
    Lint {
        /// Auto-fix what can be fixed
        #[arg(long)]
        fix: bool,
        /// Exit non-zero on errors (for CI)
        #[arg(long)]
        check: bool,
    },
}

#[cfg(test)]
mod tests {
    use super::*;
    use clap::CommandFactory;

    /// clap's structural validator. Catches misconfigurations like
    /// duplicate subcommand names, conflicting short flags, or missing
    /// help text — anything that would surface only at runtime in `--help`.
    /// Tests run before any user sees a regression.
    #[test]
    fn cli_tree_is_well_formed() {
        Cli::command().debug_assert();
    }

    /// Every subcommand at every depth must carry a non-empty description.
    /// Without this guard, a doc comment could be dropped (or never added
    /// for a new variant) and the subcommand would silently render a
    /// blank line in `--help` and the markdown reference. Walks the
    /// whole tree because nested subcommands (`config lint`, `focus on`)
    /// are just as user-facing as the top-level ones.
    #[test]
    fn every_subcommand_has_a_description() {
        fn walk(cmd: &clap::Command, path: &str) {
            let about = cmd.get_about().map(|s| s.to_string()).unwrap_or_default();
            assert!(
                !about.is_empty(),
                "subcommand `{path}` is missing a /// doc comment — clap renders blank help",
            );
            for sub in cmd.get_subcommands() {
                if sub.get_name() == "help" {
                    continue;
                }
                let nested = format!("{path} {}", sub.get_name());
                walk(sub, &nested);
            }
        }
        let cmd = Cli::command();
        for sub in cmd.get_subcommands() {
            if sub.get_name() == "help" {
                continue;
            }
            walk(sub, &format!("attend {}", sub.get_name()));
        }
    }
}
