//! `attend` CLI entry point.
//!
//! Argv parsing is handled by clap-derive (matches ADR-111's pattern for
//! the sibling `ways-cli` binary). The `Cli`/`Commands` definitions and
//! their doc comments live in `cli.rs` — that file is the canonical
//! source for runtime `--help` text AND for the markdown reference at
//! `docs/cli/attend.md` (generated by `bin/gen-docs.rs` via `clap-markdown`).
//!
//! Top-level shape:
//!   - Bare `attend` (no subcommand) prints the agent_fmt banner + help.
//!   - Every `attend X --help` is supplied automatically by clap.
//!   - The match in `main()` maps each enum variant to its `cmd::*::*`
//!     handler. Handlers take typed args directly.

mod cli;
mod cmd;
mod config;
mod config_lint;
mod emit;
mod groups;
mod identity_view;
mod scenes;
mod sensors;
mod state;
mod util;

use clap::Parser;
use cli::{Cli, Commands, ConfigCmd, FocusCmd, PermissionsCmd};
use sensors::Focus;

fn main() {
    // Bare invocation — print the agent_fmt banner + clap's auto-generated
    // help. Mirrors the ways-cli pattern (ADR-111). clap handles per-
    // subcommand `--help` automatically.
    let argv: Vec<String> = std::env::args().collect();
    let bare = argv.len() == 1;
    let top_help = argv.len() == 2 && (argv[1] == "help" || argv[1] == "--help" || argv[1] == "-h");

    if bare || top_help {
        print_banner();
        if bare {
            use clap::CommandFactory;
            let _ = Cli::command().print_help();
            println!();
            return;
        }
    }

    let cli = Cli::parse();
    let command = match cli.command {
        Some(c) => c,
        None => return,
    };

    match command {
        Commands::Run { catchup } => cmd::run::cmd_run_with_catchup(catchup),
        Commands::Peers => cmd::peers::cmd_peers(),
        Commands::Inbox { msg_id } => match msg_id {
            Some(id) => cmd::inbox::cmd_inbox_read(&id),
            None => cmd::inbox::cmd_inbox(),
        },
        Commands::Status => cmd::status::cmd_status(),
        Commands::Sensors => cmd::sensors::cmd_sensors(),
        Commands::Send { broadcast, to, focus, re, message } => {
            cmd::send::cmd_send(broadcast, to, focus, re, message);
        }
        Commands::Reply { broadcast, to, focus, message } => {
            cmd::send::cmd_reply(broadcast, to, focus, message);
        }
        Commands::Chat { passthrough } => exec_chat(passthrough),
        Commands::Focus { sub } => dispatch_focus(sub.unwrap_or(FocusCmd::List)),
        Commands::Scene { name } => cmd::scene::cmd_scene(&name),
        Commands::Scenes => cmd::scene::cmd_scenes(),
        Commands::Tune { apply } => cmd::tune::cmd_tune(apply),
        Commands::Permissions { sub } => match sub.unwrap_or(PermissionsCmd::Audit) {
            PermissionsCmd::Audit => cmd::permissions::cmd_permissions_audit(),
        },
        Commands::Cleanup { older_than, dry_run, all } => {
            cmd::cleanup::cmd_cleanup(older_than, dry_run, all);
        }
        Commands::Config { sub } => dispatch_config(sub.unwrap_or(ConfigCmd::Show)),
    }
}

fn print_banner() {
    let version = format!("v{} ({})", env!("CARGO_PKG_VERSION"), env!("ATTEND_COMMIT"));
    agent_fmt::Banner::new("ATTEND")
        .subtitle("active awareness for Claude Code sessions")
        .version(&version)
        .gradient(&agent_fmt::GRADIENT_TEAL)
        .print();
}

fn exec_chat(passthrough: Vec<String>) -> ! {
    // `attend chat` is a thin shim that execs the standalone `attend-chat`
    // binary. Keeping the iocraft dependency (and its async runtime) out of
    // the attend crate means `attend status`, `attend send`, and the sensor
    // loop stay cheap to cold-start from hooks. See ADR-120.
    #[cfg(unix)]
    {
        use std::os::unix::process::CommandExt;
        let err = std::process::Command::new("attend-chat")
            .args(&passthrough)
            .exec();
        eprintln!("attend chat: failed to launch attend-chat: {}", err);
        eprintln!("  (is `attend-chat` on PATH? run `make install` from the repo root)");
        std::process::exit(1);
    }
    #[cfg(not(unix))]
    {
        match std::process::Command::new("attend-chat")
            .args(&passthrough)
            .status()
        {
            Ok(status) => std::process::exit(status.code().unwrap_or(0)),
            Err(err) => {
                eprintln!("attend chat: failed to launch attend-chat: {}", err);
                eprintln!("  (is `attend-chat` on PATH? run `make install` from the repo root)");
                std::process::exit(1);
            }
        }
    }
}

fn dispatch_focus(sub: FocusCmd) {
    match sub {
        FocusCmd::On { name, pin } => cmd::focus::cmd_focus_on(&name, pin),
        FocusCmd::Off { name } => cmd::focus::cmd_focus_off(&name),
        FocusCmd::Clear => cmd::focus::cmd_focus_clear(),
        FocusCmd::Pin { name } => cmd::focus::cmd_focus_pin(&name),
        FocusCmd::Unpin { name } => cmd::focus::cmd_focus_unpin(&name),
        FocusCmd::Dissolve { name } => cmd::focus::cmd_focus_dissolve(&name),
        FocusCmd::All => cmd::focus::cmd_focus_all(),
        FocusCmd::List => cmd::focus::cmd_focus_list(),
    }
}

fn dispatch_config(sub: ConfigCmd) {
    match sub {
        ConfigCmd::Init => {
            let path = config::Config::init_user_config();
            println!("wrote default config to {}", path.display());
        }
        ConfigCmd::Show => {
            let focus = Focus::default_focus();
            let cfg = config::Config::load(&focus.working_dir);
            cmd::config_cmd::display_config(&cfg);
        }
        ConfigCmd::Path => {
            let home = std::env::var("XDG_CONFIG_HOME").unwrap_or_else(|_| {
                format!("{}/.config", std::env::var("HOME").unwrap_or_default())
            });
            println!("user:    {}/attend/config.yaml", home);
            let cwd = std::env::current_dir()
                .map(|p| p.to_string_lossy().to_string())
                .unwrap_or_default();
            println!("project: {}/.claude/attend.yaml", cwd);
        }
        ConfigCmd::Lint { fix, check } => {
            let code = config_lint::run(fix, check);
            if code != 0 {
                std::process::exit(code);
            }
        }
    }
}
